DROP TABLE IF EXISTS posts;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username text UNIQUE NOT NULL,
    email UNIQUE NOT NULL,
    password text NOT NULL
);